from note_templates import AnkiCardCreator

### Flashcards
## Set 1
inne = AnkiCardCreator.messengerCard(front=[
        "przepraszam",
        "przepraszam, przykro mi",
    ],
    back=[
        "Perdón",
        "Lo siento",
    ],
    deck_name='Spanish-Polish::inne',
    tags=['inne'],
    type_card="T").cards

pytania = AnkiCardCreator.messengerCard(front=[
        "kim jesteś",
        "skąd jesteś",
        "gdzie studiujesz",
        "co masz",
        "Ile lat ma?",
        "Co robi twój kuzyn?"
    ],
    back=[
        "¿quién eres?",
        "¿de dónde eres?",
        "¿dónde estudias?",
        "¿qué tienes?",
        "¿Cuántos años tiene?",
        "¿Qué hace tu primo?"
    ],
    deck_name='Spanish-Polish::pytania',
    tags=['pytania'],
    type_card="T"
).cards

osoby = AnkiCardCreator.messengerCard(front=[
        "Jaki jesteś?",
        "kręcone i blond włosy",
        "zielone oczy",
        "niebieskie oczy"
    ],
    back=[
        "¿Cómo eres?",
        "el pelo rizado y rubio",
        "ojos verdes",
        "ojos azules"
    ],
    deck_name='Spanish-Polish::osoby',
    tags=['opis_osoby'],
    type_card="T"
    ).cards

wyrazenia = AnkiCardCreator.messengerCard(front=[
        "zawsze",
        "dzisiaj chcę",
        "ja wiem, że",
        "Mam krótkie, ciemne włosy",
        "Mam zielone oczy",
        "Ona ma kręcone i blond włosy",
        "Ona ma niebieskie oczy",
        "Ona jest gruba"
    ],
    back=[
        "yo siempre",
        "hoy yo quiero",
        "Yo sé que",
        "Yo tengo pelo corto y moreno",
        "Yo tengo ojos verdes",
        "Ella tiene el pelo rizado y rubio",
        "Ella tiene ojos azules",
        "Ella es gorda"
    ],
    deck_name='Spanish-Polish::wyrazenia',
    tags=['wyrazenia'],
    type_card="T"
    ).cards

czasowniki = AnkiCardCreator.messengerCard(front=[
    "chodzić, spacerować",
    "chodzić z psem",
    "pić herbatę",
    "pływać",
    "grać w piłkę",
    "uczyć się",
    "spać",
    "śpię",
    "ja gotuję",
    "czyścić"
],
back=[
    "pasear",
    "pasear con el perro",
    "beber el té",
    "nadar",
    "jugar al fútbol",
    "estudio",
    "dormir",
    "duermo",
    "yo cocino",
    "limpio"
],
deck_name='Spanish-Polish::czasowniki',
tags=['czasowniki'],
type_card="T"
).cards

slowa = AnkiCardCreator.messengerCard(front=[
    "tydzień",
    "mama",
    "wnukowie",
    "wysoki",
    "niski",
    "gruby",
    "szczupły",
    "umięśniona",
    "blondynka",
    "włosy",
    "długie",
    "proste (włosy)",
    "brunetka",
    "ruda",
    "siwe i krótkie",
    "nosi okulary",
    "jedynaczka / jedynak",
    "zielone oczy",
    "niebieskie oczy"
],
back=[
    "la semana",
    "padre",
    "nietos",
    "alto",
    "bajo",
    "gordo",
    "delgado",
    "musculoso",
    "rubia",
    "pelo",
    "largo",
    "liso",
    "es morena",
    "es pelirroja",
    "canoso y corto",
    "tiene gafas",
    "la hija única",
    "ojos verdes",
    "ojos azules"
],
deck_name='Spanish-Polish::slowa',
tags=['slowa'],
type_card="T"
).cards

rodzina = AnkiCardCreator.messengerCard(front=[
    "rodzina",
    "ojciec",
    "matka",
    "rodzice",
    "siostra",
    "brat",
    "dziadek",
    "babcia",
    "wnuk",
    "wnuczka",
    "dziecko",
    "ciocia",
    "wujek",
    "kuzyn",
    "kuzynka",
    "maż",
    "żona",
    "syn",
    "córka",
    "rodzeństwo"
],
back=[
    "la familia",
    "el padre",
    "la madre",
    "los padres",
    "la hermana",
    "el hermano",
    "el abuelo",
    "la abuela",
    "el nieto",
    "la nieta",
    "el niño / la niña",
    "la tía",
    "el tío",
    "el primo",
    "la prima",
    "el esposo",
    "la esposa",
    "el hijo",
    "la hija",
    "los hermanos"
],
deck_name='Spanish-Polish::osoby',
tags=['opis_osoby'],
type_card="T").cards

# Set 2
wyrazenia_2 = AnkiCardCreator.messengerCard(front=[
    "Co lubisz robić?",
    "Lubię pływać",
    "Co chcesz dzisiaj robić?",
    "Jakie masz hobby?",
    "Lubię iść do biblioteki i czytać",
    "Lubię iść do biblioteki i czytać w ciszy",
    "Ciekawe, mam na myśli...",
    "Fajnie",
    "Okej",
    "Czemu nie pojedziemy do XYZ?",
    "Więc",
    "Kot znajduje się za kredensem",
    "Pies znajduje się przed obrazem",
    "Piję kawę",
    "Jesteśmy blisko morza"
],
back=[
    "¿Qué te gusta hacer?",
    "Me gusta nadar",
    "¿Qué quieres hacer hoy?",
    "¿Qué aficiones tienes?",
    "Me gusta ir a la biblioteca y leer",
    "Me gusta ir a la biblioteca y leer, en silencio",
    "Interesante, quiero decir...",
    "Guay",
    "Vale",
    "¿Por qué no vamos a XYZ?",
    "Pues",
    "El gato está detrás del armario",
    "El perro está delante de la pintura",
    "Yo bebo café",
    "Estamos cerca del mar"
],
deck_name='Spanish-Polish::wyrazenia',
tags=['wyrazenia'],
type_card='T'
).cards

pytania_2 = AnkiCardCreator.messengerCard(front=[
    "Co umiesz?",
    "Jaki masz zawód?",
    "Czy zna pani mój numer telefonu?"
],
back=[
    "¿Qué sabes hacer?",
    "¿A qué te dedicas?",
    "¿Cómo sabe usted mi número?"
],
deck_name='Spanish-Polish::pytania',
tags=['pytania'],
type_card="T"
).cards

czasowniki_2 = AnkiCardCreator.messengerCard(front=[
    "Mówić",
    "Grać w tenisa",
    "Jeździć na rowerze",
    "Podróżować",
    "Podróżuję",
    "Chcę zobaczyć XYZ"
],
back=[
    "Hablar",
    "Jugar al tenis",
    "Montar en bicicleta",
    "Viajar",
    "Viajo",
    "Yo quiero ver XYZ"
],
deck_name='Spanish-Polish::czasowniki',
tags=['czasowniki'],
type_card="T"
).cards

osoby_2 = AnkiCardCreator.messengerCard(front=[
    "Jestem fryzjerką"
],
back=[
    "Yo soy peluquera"
],
deck_name='Spanish-Polish::osoby',
tags=['osoby'],
type_card="T"
).cards

slowa_2 = AnkiCardCreator.messengerCard(front=[
    "Rower jest zielony",
    "Samochód jest czerwony",
    "Statek jest czarny",
    "Motory",
    "Dziwny",
    "Pomiędzy",
    "Księżyc",
    "Drzewo",
    "Palma"
],
back=[
    "La bicicleta es verde",
    "El coche es rojo",
    "El barco es negro",
    "Las motos",
    "Raro",
    "Entre",
    "La luna",
    "El árbol",
    "La palmera"
],
deck_name='Spanish-Polish::slowa',
tags=['slowa'],
type_card="T"
).cards

wyrazenia_3 = AnkiCardCreator.messengerCard(front=[
    "Przed",
    "Za",
    "W środku",
    "Blisko",
    "Daleko",
    "Obok",
    "Pomiędzy",
    "Pod",
    "Na (nad)",
],
back=[
    "Delante de",
    "Detrás de",
    "Dentro de",
    "Cerca de",
    "Lejos de",
    "Al lado de",
    "Entre",
    "Debajo de",
    "Encima de (=sobre)"
],
deck_name='Spanish-Polish::wyrazenia',
tags=['wyrazenia'],
type_card="T"
).cards

# Set 3
osoby_3 = AnkiCardCreator.messengerCard(front=[
    "Mąż",
    "Żona",
    "Siostrzeniec",
    "Siostrzenica",
    "Teść",
    "Czy jesteś żonaty?",
    "Moja babcia jest emerytką",
    "Mój przyjaciel jest rozwiedziony",
    "Ma ciemną skórę, blond włosy i krótkie włosy",
    "Ma niebieskie spodnie",
    "Ma czerwoną, długą sukienkę i kręcone włosy",
    "Ma krótkie, kręcone włosy, zieloną koszulę i spodnie",
    "Ma ciemną skórę, krótkie włosy i niebieskie spodnie"
],
back=[
    "Marido",
    "Mujer",
    "Sobrino",
    "Sobrina",
    "Suegro",
    "¿Estás casado?",
    "Mi abuela es jubilada",
    "Mi amigo es divorciado",
    "Está la piel oscura, rubio y pelo corto",
    "Tienes los pantalones azules",
    "Tiene el vestido rojo y largo, rizado pelo",
    "Tiene el pelo corto y rizado, una camisa verde y los pantalones",
    "Tiene piel oscura, corto pelo y los pantalones azules"
],
deck_name='Spanish-Polish::osoby',
tags=['osoby'],
type_card="T"
).cards

wyrazenia_4 = AnkiCardCreator.messengerCard(front=[
    "Co robisz w weekendy?",
    "Tańczę w weekendy",
    "Czytam książkę w weekendy",
    "Śpię w weekendy",
    "Jeżdżę na rowerze w weekendy",
    "Rozmawiam w weekendy",
    "Pracuję w weekendy",
    "Idę na plażę w weekendy"
],
back=[
    "¿Qué haces los fines de semana?",
    "Yo bailo los fines de semana",
    "Los fines de semana yo leo libro",
    "Estoy durmiendo los fines de semana",
    "Yo ando en bicicleta los fines de semana",
    "Yo hablo los fines de semana",
    "Yo trabajo los fines de semana",
    "Yo voy a la playa los fines de semana"
],
deck_name='Spanish-Polish::wyrazenia',
tags=['wyrazenia'],
type_card="T"
).cards

# Set 4
osoby_4 = AnkiCardCreator.messengerCard(front=[
    "Hola",
    "Buenos días",
    "Buenas tardes",
    "Buenas noches",
    "Adiós",
    "Hasta luego",
    "Nos vemos",
    "Hasta pronto",
    "Hasta la vista",
    "Hasta la próxima",
    "Hasta mañana",
    "Hasta el viernes",
    "Cuídate",
    "Te veo luego",
    "¿Qué tal?",
    "¿Cómo estás?",
    "¿Y tú?",
    "¿Cómo te llamas?",
    "¿Dónde vives?",
    "¿De dónde eres?",
    "Estoy genial",
    "Estoy muy bien",
    "Estoy bien",
    "Estoy regular",
    "Estoy mal",
    "Estoy fatal",
    "Me llamo Konrad",
    "Vivo en Łódź",
    "Soy de Polonia",
    "¿Quién es?",
    "Esta es...",
    "Este es....",
    "Mucho gusto",
    "Señor",
    "Señorita",
    "¿Qué nacionalidad eres?",
    "¿Ella es española?",
    "¿Qué estudias?",
    "Yo también",
    "¿Qué te interesa?",
    "¿Qué haces?",
    "Voy al trabajo",
    "¿Dónde trabaja?",
    "¿Te gusta el ....?",
    "Te amo ...",
    "Te quiero",
    "¿Cómo se escribe...?",
    "¿Cómo se dice ... en español?",
    "¿Qué significa....?",
    "¿Puedo abrir la ventana?",
    "No entiendo",
    "¿Puedes repetir?"
  ],
  back= [
    "Cześć",
    "Dzień dobry (do obiadu)",
    "dzień dobry (po obiedzie)",
    "Dobry wieczór",
    "Do widzenia",
    "na razie",
    "do zobaczenia",
    "do zobaczenia wkrótce",
    "Do widzenia",
    "Do następnego razu",
    "do jutra",
    "do piątku",
    "uważaj na siebie, dbaj o siebie",
    "do zobaczenia później",
    "jak tam, jak leci?",
    "Jak się masz, jak się miewasz",
    "a ty?",
    "Jak się nazywasz",
    "Gdzie mieszkasz?",
    "Skąd jesteś",
    "czuję się świetnie",
    "czuję się bardzo dobrze",
    "czuję się w porządku, dobrze",
    "czuję się przeciętnie",
    "źle się czuję",
    "czuję się fatalnie",
    "Mam na imię Konrad, Nazywam się Konrad",
    "Mieszkam w Łodzi",
    "Pochodzę z Polski, Jestem z Polski",
    "kto to jest?",
    "to jest.... (kobieta)",
    "to jest.... (mężczyzna)",
    "bardzo mi miło",
    "pan",
    "panienka",
    "Jakiej jesteś narodowości?",
    "czy jest Hiszpanką?",
    "co studiujesz?",
    "Ja też",
    "Co cię interesuje, czym się interesujesz?",
    "Co robisz?",
    "idę do pracy",
    "gdzie pracuje?",
    "lubisz ....?",
    "kocham ... (wyznanie miłości)",
    "kocham, chcę",
    "jak się pisze...",
    "jak się mówi .... po hiszpańsku",
    "co znaczy .....?",
    "mogę otworzyć okno?",
    "nie rozumiem",
    "możesz powtórzyć?"
  ],
  deck_name= "Spanish-Polish::osoby",
  tags= [],
  type_card= "T"
).cards

slowa_3 = AnkiCardCreator.messengerCard(
  front=[
    "Mirar",
    "También",
    "Ingeniero",
    "Tapas",
    "Pero",
    "El perro",
    "Trabajar",
    "Hacer",
    "Hablar",
    "Vivir",
    "Ser",
    "Llamarse",
    "Continentes",
    "España",
    "Polonia",
    "Austria",
    "Francia",
    "Inglaterra",
    "Italia",
    "Alemania",
    "Argentina",
    "China",
    "Panamá",
    "Brasil",
    "Canadá",
    "Estados Unidos",
    "País",
    "(El señor es) español",
    "(El señor es) polaco",
    "(El señor es) austriaco",
    "(El señor es) francés",
    "(El señor es) inglés",
    "(El señor es) alemán",
    "(El señor es) italiano",
    "(El señor es) argentino",
    "(El señor es) chino",
    "(El señor es) panameño",
    "(El señor es) brasileño",
    "(El señor es) canadiense",
    "(El señor es) estadounidense",
    "(La señora es) española",
    "(La señora es) polaca",
    "(La señora es) austriaca",
    "(La señora es) francesa",
    "(La señora es) inglesa",
    "(La señora es) italiana",
    "(La señora es) alemana",
    "(La señora es) argentina",
    "(La señora es) china",
    "(La señora es) panameña",
    "(La señora es) brasileña",
    "(La señora es) canadiense",
    "(La señora es) estadounidense",
    "Vale",
    "Bueno",
    "Claro",
    "Por favor",
    "Porque",
    "El abogado",
    "Bombero",
    "El dependiente",
    "El economista",
    "El contable",
    "El camarero",
    "El cocinero",
    "El estudiante",
    "El profesor",
    "El médico",
    "El enfermero",
    "El director",
    "El secretario",
    "El azafato",
    "El piloto",
    "El policía",
    "El recepcionista",
    "La empresa",
    "El hospital",
    "El banco",
    "El restaurante",
    "La escuela",
    "El bufete de abogados",
    "El hotel",
    "La tienda",
    "El aeropuerto",
    "La comisaría",
    "Mar",
    "Café",
    "Odio",
    "El té",
    "Tus",
    "Escuchar",
    "Cantar",
    "Bailar",
    "Desayunar",
    "Cocinar",
    "Leer",
    "Enfermo",
    "Ocupado",
    "Cansado",
    "Poco",
    "Uno",
    "Dos",
    "Tres",
    "Cuatro",
    "Cinco",
    "Seis",
    "Siete",
    "Ocho",
    "Nueve",
    "Diez",
    "Once",
    "Doce",
    "Trece",
    "Catorce",
    "Quince",
    "Dieciséis",
    "Diecisiete",
    "Dieciocho",
    "Diecinueve",
    "Veinte",
    "Veintiuno",
    "Veintidós",
    "Veintitrés",
    "Veinticuatro",
    "Veinticinco",
    "Veintiséis",
    "Veintisiete",
    "Veintiocho",
    "Veintinueve",
    "Treinta",
    "La semana",
    "Pasear",
    "Pasear con el perro",
    "Beber el té",
    "Nadar",
    "Jugar al fútbol",
    "Estudio",
    "Yo siempre",
    "Dormir",
    "Duermo",
    "Yo cocino"
  ],
  back= [
    "patrzeć",
    "też, również",
    "inżynier",
    "przekąski (z alkoholem)",
    "ale",
    "pies",
    "pracować",
    "robić",
    "mówić",
    "mieszkać",
    "być",
    "nazywać się",
    "kontynenty",
    "Hiszpania",
    "Polska",
    "Austria",
    "Francja",
    "Anglia",
    "Włochy",
    "Niemcy",
    "Argentyna",
    "Chiny",
    "Panama",
    "Brazylia",
    "Kanada",
    "Stany Zjednoczone",
    "kraj",
    "Hiszpan",
    "Polak",
    "Austriak",
    "Francuz",
    "Anglik, Brytyjczyk",
    "Niemiec",
    "Włoch",
    "Argentyńczyk",
    "Chińczyk",
    "Panamczyk",
    "Brazylijczyk",
    "Kanadyjczyk",
    "Amerykanin",
    "Hiszpanka",
    "Polka",
    "Austriaczka",
    "Francuzka",
    "Brytyjka, Angielka",
    "Włoszka",
    "Niemka",
    "Argentynka",
    "Chinka",
    "Panamka",
    "Brazylijka",
    "Kanadyjka",
    "Amerykanka",
    "okej, w porządku",
    "dobrze",
    "jasne",
    "bardzo proszę",
    "ponieważ, aby",
    "adwokat",
    "strażak",
    "sprzedawca",
    "ekonomista",
    "księgowy",
    "kelner",
    "kucharz",
    "uczeń",
    "profesor, nauczyciel",
    "lekarz",
    "pielęgniarz, sanitariusz",
    "dyrektor",
    "sekretarz",
    "steward",
    "pilot",
    "policjant",
    "recepcjonista",
    "firma",
    "szpital",
    "bank",
    "restauracja",
    "szkoła",
    "kancelaria prawnicza",
    "hotel",
    "sklep",
    "lotnisko",
    "komisariat policji",
    "morze",
    "kawa",
    "nie cierpię",
    "herbata",
    "twoi, twoje",
    "słuchać",
    "śpiewać",
    "tańczyć",
    "jeść śniadanie",
    "gotować",
    "czytać",
    "chory",
    "zajęty",
    "zmęczony",
    "trochę",
    "jeden",
    "dwa",
    "trzy",
    "cztery",
    "pięć",
    "sześć",
    "siedem",
    "osiem",
    "dziewięć",
    "dziesięć",
    "jedenaście",
    "dwanaście",
    "trzynaście",
    "czternaście",
    "piętnaście",
    "szesnaście",
    "siedemnaście",
    "osiemnaście",
    "dziewiętnaście",
    "dwadzieścia",
    "dwadzieścia jeden",
    "dwadzieścia dwa",
    "dwadzieścia trzy",
    "dwadzieścia cztery",
    "dwadzieścia pięć",
    "dwadzieścia sześć",
    "dwadzieścia siedem",
    "dwadzieścia osiem",
    "dwadzieścia dziewięć",
    "trzydzieści",
    "tydzień",
    "chodzić, spacerować",
    "chodzić z psem",
    "pić herbatę",
    "pływać",
    "grać w piłkę",
    "uczyć się",
    "zawsze",
    "spać",
    "śpię",
    "gotuję"
  ],
  deck_name= "Spanish-Polish::slowa",
  tags= [],
  type_card= "T"
).cards



### Sets
set_1 = [inne, pytania, osoby, wyrazenia, czasowniki, slowa, rodzina]
set_2 = [wyrazenia_2, wyrazenia_3, pytania_2, czasowniki_2, osoby_2, slowa_2]
set_3 = [osoby_3, wyrazenia_4]
set_4 = [osoby_4, slowa_3]
